import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  scrollContent: { paddingBottom: 100 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20 },
  inviteRow: { flexDirection: 'row', justifyContent: 'flex-end', paddingHorizontal: 20, marginBottom: 20, gap: 8 },
  inviteCodeBadge: { paddingVertical: 6, paddingHorizontal: 12, borderRadius: 15, borderWidth: 1, borderColor: '#E0D5FF', borderStyle: 'dashed' },
  inviteText: { fontSize: 15, color: '#000' },
  purpleText: { color: '#9747FF', fontWeight: 'bold' },
  manualButton: { backgroundColor: '#E0D5FF99', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 15 },
  manualButtonText: { fontSize: 15, color: '#9747FF', fontWeight: 'bold' },
  section: { marginBottom: 25, paddingHorizontal: 20 },
  sectionTitle: { fontSize: 25, fontWeight: 'bold', color: '#000', marginBottom: 5 },
  dateText: { fontSize: 15, color: '#AFAFAF', marginBottom: 20 },
  salaryContainer: { alignItems: 'center', paddingVertical: 10 },
  salaryAmount: { fontSize: 35, fontWeight: 'bold', color: '#000', marginBottom: 8 },
  salaryDesc: { fontSize: 15, color: '#000' },
  blueText: { color: '#0088FF', fontWeight: 'bold' },
  statusText: { fontSize: 15, color: '#AFAFAF', marginBottom: 15 },
  checkInButton: { backgroundColor: '#E0D5FF99', width: '100%', height: 60, borderRadius: 50, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  checkInButtonText: { fontSize: 25, fontWeight: 'bold', color: '#000' },
  locationRow: { flexDirection: 'row', justifyContent: 'center', gap: 15 },
  todoItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 10, paddingVertical: 4 },
  checkbox: { width: 18, height: 18, borderRadius: 4, borderWidth: 1.5, borderColor: '#C0C0C0', marginRight: 10 },
  todoText: { fontSize: 15, color: '#000' },
  inputContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#E0D5FF99', borderRadius: 25, paddingHorizontal: 12, marginTop: 10, height: 45 },
  input: { flex: 1, fontSize: 14, color: '#000', marginRight: 10 },
  horizontalScroll: { paddingRight: 20 },
  bottomTab: { position: 'absolute', bottom: 0, width: '100%', height: 80, backgroundColor: '#fff', flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#eee', paddingBottom: 15 },
});