export const NOTIFICATIONS = [
  {
    id: 1,
    icon: '📝',
    name: '근로계약서',
    message: '사장님이 근로계약서를 보냈습니다. 내용을 확인하고 서명해 주세요.',
    time: '2시간 전',
    category: '오늘',
    isRead: false,
  },
  {
    id: 2,
    icon: '✅',
    name: '계약 완료',
    message: '계약 작성이 완료되었습니다! 이제 안전하게 근무를 시작해 보세요.',
    time: '2시간 전',
    category: '오늘',
    isRead: false,
  },
  {
    id: 3,
    icon: '💰',
    name: '급여 안내',
    message: '이번달 예정 월급을 확인해 보세요.',
    time: '3시간 전',
    category: '오늘',
    isRead: false,
  },
  {
    id: 4,
    icon: '💸',
    name: '급여 입금',
    message: '이번 달 급여 명세서가 도착했습니다! 한 달 동안 고생많으셨어요!',
    time: '어제',
    category: '어제',
    isRead: true,
  },
  {
    id: 5,
    icon: '🟢',
    name: '출근 완료',
    message: '(09:02) 출근 완료! 오늘도 기분 좋은 하루 되세요.',
    time: '어제',
    category: '어제',
    isRead: true,
  },
  {
    id: 6,
    icon: '👋',
    name: '퇴근 완료',
    message: '(18:00) 퇴근 완료! 고생하셨습니다. 조심히 들어가세요!',
    time: '어제',
    category: '어제',
    isRead: true,
  },
];